title: Ian's Personal Blog
description: Personal notes, implementations, and reflections.
baseurl: ""  # Important: leave empty if using GitHub Pages at username.github.io
url: "https://your-username.github.io"

theme: minima

# Navigation (Minima theme)
header_pages:
  - study/index.md
  - projects/index.md
  - thoughts/index.md

# Optional: social links or future blog settings

